nyc-kingdom/kingdom-server

package.json
server/api/checkin.js
server/api/establishment.js
server/api/index.js
server/api/users.js
server/db/models/checkin.js

Establishment routes

---

server/api/users.spec.js
server/auth/foursquare.js
server/auth/index.js
server/db/models/user.js
server/db/models/user.spec.js
webpack.config.js

Login four

---

package-lock.json
package.json
server/api/checkin.js
server/api/establishment.js
server/api/users.js
server/auth/foursquare.js
server/auth/index.js
server/db/models/checkin.js
server/db/models/user.js
server/index.js

Set user on state

---

server/api/users.js
server/auth/foursquare.js

fixed bugs

---

package-lock.json
package.json
server/api/checkins.js
server/db/models/checkin.js
server/db/models/index.js
server/db/models/kingdom.js

added gabes changes and made kingdom db

---

server/api/castles.js
server/api/checkins.js
server/api/establishments.js
server/api/index.js
server/api/users.js
server/db/models/castle.js
server/db/models/checkin.js
server/db/models/establishment.js
server/db/models/index.js
server/db/models/kingdom.js
server/db/models/user.js

set up castles

---

script/seed.js
server/api/checkins.js
server/auth/index.js
server/db/models/establishment.js
server/db/models/user.js
server/index.js

adjusted checkin logic

---

script/seed.js
server/api/establishments.js
server/db/models/establishment.js
server/db/models/user.js
server/index.js

fixed seed file

---

script/seed.js
server/api/establishments.js
server/db/models/checkin.js

Checkin array

---

server/api/checkins.js
server/api/index.js
server/api/markers.js
server/auth/foursquare.js

mirgated search query to back end

---

server/api/users.js

user now has kingdom when signin

---

server/auth/foursquare.js

connection

---

script/seed.js
server/api/checkins.js
server/api/establishments.js
server/db/models/checkin.js
server/db/models/establishment.js
server/db/models/index.js

Migrate foursquare checkins

---

server/db/models/establishment.js

one more change

---

server/api/markers.js
server/db/models/establishment.js
server/socket/index.js

This commit sets up a socket listener to receive 'check-in events and then broadcast them to all users to update their view'

Added socket functionality to see check-ins

---

server/api/checkins.js
server/api/establishments.js
server/db/models/checkin.js
server/db/models/establishment.js
server/db/models/kingdom.js

Refactor checkins

---

script/seed.js
server/api/users.js
server/db/models/user.js

profile username

---

server/api/establishments.js
server/api/index.js
server/api/leaderboard.js
server/db/models/checkin.js
server/db/models/establishment.js
server/db/models/kingdom.js

Leaderboard

---

package.json
server/index.js

fixed heroku issues

---

server/auth/foursquare.js
server/index.js

Fix express static

---

server/api/checkins.js
server/api/establishments.js
server/socket/index.js

This commit fixes a route to eagerly load a check-in when coming back to front-end state

Eager load

---

server/auth/foursquare.js
server/auth/index.js
server/index.js

fixed dev mode

---

server/db/models/establishment.js

fixed allegiance to name

---

package-lock.json
package.json
script/seed.js
server/auth/foursquare.js
server/index.js
server/socket/index.js

Cors middleware

---

script/seed.js
server/api/establishments.js
server/auth/index.js
server/db/models/kingdom.js
server/db/models/user.js
server/index.js

fixed linter errors

---

server/api/checkins.js
server/api/establishments.js
server/api/users.js
server/db/models/castle.js
server/db/models/establishment.js
server/db/models/kingdom.js

finished editKingdom

---

server/db/models/index.js
server/db/models/shield.js

shield database

---

server/api/establishments.js
server/api/shields.js

shield api

---

server/api/users.js

clean coding

---

package.json
server/auth/index.js

package.json scripts

---

package.json

based on Heroku allow

---

server/auth/index.js
server/db/models/kingdom.js

move kingdom logic from components

---

server/db/models/establishment.js
server/db/models/kingdom.js

used based on info

---

server/index.js

from http to https in production

---

server/db/models/kingdom.js
server/index.js

checking some error

---

server/api/establishments.js
server/api/users.js
server/auth/foursquare.js

Kingdom name with state

---

package-lock.json
package.json

fixed dependency vulnerability
